# TensorFlow with Contrib.Learn

In [15]:
import tensorflow.contrib.learn as learn

In [16]:
from sklearn.datasets import load_iris

In [17]:
import tensorflow as tf
import numpy as np

In [18]:
iris = learn.datasets.load_dataset('iris')

In [19]:
X = iris.data
y = iris.target

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [22]:
# Let's run a Deep Neural Network Classifier
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)

In [23]:
# Create a DNN of 3 hidden layers of 20 neurons eachs
classifier = learn.DNNClassifier(feature_columns=feature_columns, hidden_units=[20,20,20], n_classes=3)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c237ce630>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/gf/bvnvfh0s21x1yrbw8vsz0mt00000gn/T/tmpehlle_hr'}


In [24]:
classifier.fit(X_train, y_train, steps=1000, batch_size=64)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/gf/bvnvfh0s21x1yrbw8vsz0mt00000gn/T/tmpehlle_hr/model.ckpt.
INFO:tensorflow:loss = 1.13973, step = 1
INFO:tensorflow:global_step/sec: 1171.7
INFO:tensorflow:loss = 0.22831, step = 101 (0.086 sec)
INFO:tensorflow:global_step/sec: 1328.27
INFO:tensorflow:loss = 0.085371, step = 201 (0.075 sec)
INFO:tensorflow:global_step/sec: 1334.1
INFO:tensorflow:loss = 0.161352, step = 301 (0.075 sec)
INFO:tensorflow:global_step/sec: 1301.75
INFO:tensorflow:loss = 0.105845, step = 401 (0.076 sec)
INFO:tensorflow:global_step/sec: 1262.13
INFO:tensorflow:loss = 0.113686, step = 501 (0.079 sec)
INFO:tensorflow:global_step/sec: 1307.19
INFO:tensorflow:loss = 0.0921081, step = 601 (0.076 sec)
INFO:tensorflow:global_step/sec: 1292.66
INFO:tensorflow:loss = 0.048911, step = 701 (0.077 sec)
INFO:tensorflow:global_step/sec: 1343.83
INFO:tensorflow:loss = 0.0424674, step = 801 (0.075 sec)
INFO:tensorflow:globa

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x1c23e1f668>, 'hidden_units': [20, 20, 20], 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float64, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x11beb3950>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [25]:
iris_predictions = list(classifier.predict(X_test, as_iterable=True))

INFO:tensorflow:Restoring parameters from /var/folders/gf/bvnvfh0s21x1yrbw8vsz0mt00000gn/T/tmpehlle_hr/model.ckpt-1000


In [26]:
print(iris_predictions)

[1, 1, 0, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 0, 1, 0, 2, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 0, 2, 1, 2, 0, 1, 0]


In [27]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
print(classification_report(y_test, iris_predictions))
print("\n")
print(confusion_matrix(y_test, iris_predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00        17

avg / total       1.00      1.00      1.00        45



[[15  0  0]
 [ 0 13  0]
 [ 0  0 17]]
